// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YakinduReleaseTo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "YakinduReleaseTo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace modes3 {
namespace protobuf {
class YakinduReleaseToDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<YakinduReleaseTo> {
} _YakinduReleaseTo_default_instance_;

namespace protobuf_YakinduReleaseTo_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(YakinduReleaseTo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(YakinduReleaseTo, targetid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(YakinduReleaseTo, direction_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(YakinduReleaseTo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_YakinduReleaseTo_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "YakinduReleaseTo.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _YakinduReleaseTo_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::modes3::protobuf::protobuf_Enums_2eproto::InitDefaults();
  _YakinduReleaseTo_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\026YakinduReleaseTo.proto\022\017modes3.protobu"
      "f\032\013Enums.proto\"d\n\020YakinduReleaseTo\022\020\n\010ta"
      "rgetID\030\001 \001(\r\022>\n\tdirection\030\002 \001(\0162+.modes3"
      ".protobuf.YakinduConnectionDirectionB0\n,"
      "hu.bme.mit.inf.modes3.messaging.mms.mess"
      "agesP\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 214);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "YakinduReleaseTo.proto", &protobuf_RegisterTypes);
  ::modes3::protobuf::protobuf_Enums_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_YakinduReleaseTo_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int YakinduReleaseTo::kTargetIDFieldNumber;
const int YakinduReleaseTo::kDirectionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

YakinduReleaseTo::YakinduReleaseTo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_YakinduReleaseTo_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:modes3.protobuf.YakinduReleaseTo)
}
YakinduReleaseTo::YakinduReleaseTo(const YakinduReleaseTo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&targetid_, &from.targetid_,
    reinterpret_cast<char*>(&direction_) -
    reinterpret_cast<char*>(&targetid_) + sizeof(direction_));
  // @@protoc_insertion_point(copy_constructor:modes3.protobuf.YakinduReleaseTo)
}

void YakinduReleaseTo::SharedCtor() {
  ::memset(&targetid_, 0, reinterpret_cast<char*>(&direction_) -
    reinterpret_cast<char*>(&targetid_) + sizeof(direction_));
  _cached_size_ = 0;
}

YakinduReleaseTo::~YakinduReleaseTo() {
  // @@protoc_insertion_point(destructor:modes3.protobuf.YakinduReleaseTo)
  SharedDtor();
}

void YakinduReleaseTo::SharedDtor() {
}

void YakinduReleaseTo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* YakinduReleaseTo::descriptor() {
  protobuf_YakinduReleaseTo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_YakinduReleaseTo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const YakinduReleaseTo& YakinduReleaseTo::default_instance() {
  protobuf_YakinduReleaseTo_2eproto::InitDefaults();
  return *internal_default_instance();
}

YakinduReleaseTo* YakinduReleaseTo::New(::google::protobuf::Arena* arena) const {
  YakinduReleaseTo* n = new YakinduReleaseTo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void YakinduReleaseTo::Clear() {
// @@protoc_insertion_point(message_clear_start:modes3.protobuf.YakinduReleaseTo)
  ::memset(&targetid_, 0, reinterpret_cast<char*>(&direction_) -
    reinterpret_cast<char*>(&targetid_) + sizeof(direction_));
}

bool YakinduReleaseTo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:modes3.protobuf.YakinduReleaseTo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 targetID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &targetid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.YakinduConnectionDirection direction = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_direction(static_cast< ::modes3::protobuf::YakinduConnectionDirection >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:modes3.protobuf.YakinduReleaseTo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:modes3.protobuf.YakinduReleaseTo)
  return false;
#undef DO_
}

void YakinduReleaseTo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:modes3.protobuf.YakinduReleaseTo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 targetID = 1;
  if (this->targetid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->targetid(), output);
  }

  // .modes3.protobuf.YakinduConnectionDirection direction = 2;
  if (this->direction() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->direction(), output);
  }

  // @@protoc_insertion_point(serialize_end:modes3.protobuf.YakinduReleaseTo)
}

::google::protobuf::uint8* YakinduReleaseTo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:modes3.protobuf.YakinduReleaseTo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 targetID = 1;
  if (this->targetid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->targetid(), target);
  }

  // .modes3.protobuf.YakinduConnectionDirection direction = 2;
  if (this->direction() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->direction(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:modes3.protobuf.YakinduReleaseTo)
  return target;
}

size_t YakinduReleaseTo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:modes3.protobuf.YakinduReleaseTo)
  size_t total_size = 0;

  // uint32 targetID = 1;
  if (this->targetid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->targetid());
  }

  // .modes3.protobuf.YakinduConnectionDirection direction = 2;
  if (this->direction() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->direction());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void YakinduReleaseTo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:modes3.protobuf.YakinduReleaseTo)
  GOOGLE_DCHECK_NE(&from, this);
  const YakinduReleaseTo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const YakinduReleaseTo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:modes3.protobuf.YakinduReleaseTo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:modes3.protobuf.YakinduReleaseTo)
    MergeFrom(*source);
  }
}

void YakinduReleaseTo::MergeFrom(const YakinduReleaseTo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:modes3.protobuf.YakinduReleaseTo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.targetid() != 0) {
    set_targetid(from.targetid());
  }
  if (from.direction() != 0) {
    set_direction(from.direction());
  }
}

void YakinduReleaseTo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:modes3.protobuf.YakinduReleaseTo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void YakinduReleaseTo::CopyFrom(const YakinduReleaseTo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:modes3.protobuf.YakinduReleaseTo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool YakinduReleaseTo::IsInitialized() const {
  return true;
}

void YakinduReleaseTo::Swap(YakinduReleaseTo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void YakinduReleaseTo::InternalSwap(YakinduReleaseTo* other) {
  std::swap(targetid_, other->targetid_);
  std::swap(direction_, other->direction_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata YakinduReleaseTo::GetMetadata() const {
  protobuf_YakinduReleaseTo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_YakinduReleaseTo_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// YakinduReleaseTo

// uint32 targetID = 1;
void YakinduReleaseTo::clear_targetid() {
  targetid_ = 0u;
}
::google::protobuf::uint32 YakinduReleaseTo::targetid() const {
  // @@protoc_insertion_point(field_get:modes3.protobuf.YakinduReleaseTo.targetID)
  return targetid_;
}
void YakinduReleaseTo::set_targetid(::google::protobuf::uint32 value) {
  
  targetid_ = value;
  // @@protoc_insertion_point(field_set:modes3.protobuf.YakinduReleaseTo.targetID)
}

// .modes3.protobuf.YakinduConnectionDirection direction = 2;
void YakinduReleaseTo::clear_direction() {
  direction_ = 0;
}
::modes3::protobuf::YakinduConnectionDirection YakinduReleaseTo::direction() const {
  // @@protoc_insertion_point(field_get:modes3.protobuf.YakinduReleaseTo.direction)
  return static_cast< ::modes3::protobuf::YakinduConnectionDirection >(direction_);
}
void YakinduReleaseTo::set_direction(::modes3::protobuf::YakinduConnectionDirection value) {
  
  direction_ = value;
  // @@protoc_insertion_point(field_set:modes3.protobuf.YakinduReleaseTo.direction)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace modes3

// @@protoc_insertion_point(global_scope)
